### ISSUE TITLE
Crash with NEI

### ISSUE THREAD

**Issue by BrisingrAerowing** [CD4017BE/InductiveLogistics#3]
Got the following stack trace when using this mod with NEI:

``` text
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Not Enough Items (nei)

Caused by: java.lang.ArrayIndexOutOfBoundsException: 32767
	at cd4017be.indlog.item.ItemTank.initCapabilities(ItemTank.java:53) ~[ItemTank.class:?]
	at net.minecraft.item.ItemStack.forgeInit(ItemStack.java:1215) ~[aip.class:?]
	at net.minecraft.item.ItemStack.<init>(ItemStack.java:112) ~[aip.class:?]
	at net.minecraft.item.ItemStack.<init>(ItemStack.java:98) ~[aip.class:?]
	at codechicken.lib.inventory.InventoryUtils.newItemStack(InventoryUtils.java:52) ~[InventoryUtils.class:?]
	at codechicken.nei.util.ItemStackMap.wildcard(ItemStackMap.java:224) ~[ItemStackMap.class:?]
	at codechicken.nei.util.ItemStackSet.with(ItemStackSet.java:23) ~[ItemStackSet.class:?]
	at codechicken.nei.init.NEIInitialization.loadModSubsets(NEIInitialization.java:329) ~[NEIInitialization.class:?]
	at codechicken.nei.init.NEIInitialization.bootNEI(NEIInitialization.java:73) ~[NEIInitialization.class:?]
	at codechicken.nei.proxy.ProxyClient.loadComplete(ProxyClient.java:54) ~[ProxyClient.class:?]
	at codechicken.nei.NotEnoughItems.loadComplete(NotEnoughItems.java:62) ~[NotEnoughItems.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606) ~[forge-1.12.2-14.23.0.2515-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253) ~[forge-1.12.2-14.23.0.2515-universal.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231) ~[forge-1.12.2-14.23.0.2515-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:727) ~[Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:348) ~[FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[1.12.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) ~[OneSixLauncher.class:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) ~[OneSixLauncher.class:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) ~[EntryPoint.class:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) ~[EntryPoint.class:?]
```

No actual crash log. This was on world load and the game went into an undefined state.

I'm not sure if this is NEIs fault or Inductive Logistics' fault.

MC 1.12.2
Forge 2515

**Comment by CD4017BE** [comment]
This tells me, I shouldn't trust that my Items are always instantiated with a valid damage value.
