### ISSUE TITLE
NullPointerException on server load

### ISSUE THREAD

**Issue by coldino** [CD4017BE/InductiveLogistics#40]
Hoping there's still someone listening here...

### What I did:
Used Inductive Logistics advanced pipes extensively, connected to many things. 

### What happened:
Restarted the server one day and got a NullPointerException. Unable to work out exactly which connection causes the issue as I'm unable to load that area at all.

```
[15:04:41] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at cd4017be.indlog.multiblock.FluidSource.findFluid(FluidSource.java:50) ~[FluidSource.class:?]
	at cd4017be.indlog.multiblock.WarpPipeNetwork.extractFluid(WarpPipeNetwork.java:227) ~[WarpPipeNetwork.class:?]
	at cd4017be.indlog.multiblock.FluidInjector.tick(FluidInjector.java:62) ~[FluidInjector.class:?]
	at cd4017be.lib.TickRegistry.tick(TickRegistry.java:71) ~[TickRegistry.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1985_TickRegistry_tick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```

This struck me as likely to be similar to a previous issue where sources were not ready to supply fluid in the first ticks after server startup.

Looking at the [source](https://github.com/CD4017BE/InductiveLogistics/blob/ad3036f7f6ba7e9b9af79819ac10a484c71eb2ef/src/java/cd4017be/indlog/multiblock/FluidSource.java#L50), I see a number of null checks, but there's one case that might be the issue: you are iterating over the result of `acc.getTankProperties()` without checking it.

Sadly my Java-fu isn't strong enough to get the source compiling, so I can't test this theory. Just can't get InductiveLogistics to find CD4017BE_lib.

### Used Versions:
- Minecraft-1.12.2
- InductiveLogistics-1.3.3
- CD4017BE_lib-6.4.6
- Forge-2838
- Pack- SevTech Ages 3.1.2

**Comment by CD4017BE** [comment]
fix released
